# .readthedocs.yaml
version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.8' # 指定 Python 版本

# 设置 Python 环境
sphinx:
  configuration: docs/conf.py # 指定 Sphinx 配置文件路径
  fail_on_warning: false # 可选：警告是否视为构建失败

# 安装项目依赖（如果需要）
python:
  install:
    - requirements: requirements/docs.txt
