version: '3'
services:
  webapp:
    build: .
    restart: always
    ports:
      - "9514:9514"
    environment:
      - sapic_redis_url=redis://@redis:6379
      # 设置信任代理标头
      #- sapic_proxyfix=true
    volumes:
      - static:/picbed/static/
      - /data/picbed/:/picbed/static/upload/
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data/picbed/redis/data/:/data/
volumes:
  static: