---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapic-deploy
  labels:
    app: sapic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapic
  template:
    metadata:
      labels:
        app: sapic
      annotations:
        port: "9514"
        python: "3.8"
        github: "sapicd/sapic"
    spec:
      containers:
        - name: sapic
          image: docker.io/staugur/sapic:latest
          env:
            - name: sapic_redis_url     # redis服务IP地址
              value: "redis://@redis"
            #设置信任代理标头
            #- name: sapic_proxyfix      
            #  value: "true"
          ports:
            - containerPort: 9514
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 9514
              path: /api/index
            initialDelaySeconds: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 9514
              path: /api/index
            initialDelaySeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sapic-svc
  labels:
    app: sapic
spec:
  selector:
    app: sapic
  ports:
  - name: sapic-port
    protocol: TCP
    port: 9514
    targetPort: 9514
  #在Node上映射一个端口
  #type: NodePort
